name: PlatformIO Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Install XIAO BLE
        run: |
          pio platform install nordicnrf52
          curl -OL https://gist.githubusercontent.com/alwint3r/63594345ca86a81a810ca7bcaeae23d9/raw/9aaf34cec27683395bc3e62296769cd7fdb6b1e8/xiaoblesense.json
          ls ~/.platformio
          mv  xiaoblesense.json ~/.platformio/platforms/nordicnrf52/boards
          curl -OL https://files.seeedstudio.com/arduino/core/nRF52840/Seeed_XIAO_BLE_nRF52840_Sense261.tar.bz2
          tar -xjf Seeed_XIAO_BLE_nRF52840_Sense261.tar.bz2
          cp -r 2.6.1/* ~/.platformio/packages/framework-arduino-mbed
          curl -OL https://gist.githubusercontent.com/botamochi6277/9758fb94483f7cdf28639f9c80902674/raw/505fa2bad210ab288afb5de5a7396f66b9fc1b27/platform.py
          mv platform.py ~/.platformio/platforms/nordicnrf52/platform.py
      - name: Install library dependencies
        run: pio lib -g install 1
      - name: Run PlatformIO
        run: pio run
