name: PlatformIO Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Install XIAO BLE
        run: |
          pio platform install nordicnrf52
          curl -OL https://gist.githubusercontent.com/alwint3r/63594345ca86a81a810ca7bcaeae23d9/raw/9aaf34cec27683395bc3e62296769cd7fdb6b1e8/xiaoblesense.json
          ls ~/.platformio
          mv  xiaoblesense.json ~/.platformio/platforms/nordicnrf52/boards
          sed 's/"nicla_sense_me"/ "nicla_sense_me", "xiaoblesense"/g' .platformio/platforms/nordicnrf52/platform.py
      - name: Install library dependencies
        run: pio lib -g install 1
      - name: Run PlatformIO
        run: pio run
